# frozen_string_literal: true

source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails', branch: 'main'
gem 'rails', '~> 7.2.2', '>= 7.2.2.1'
# Use postgresql as the database for Active Record
gem 'pg', '~> 1.1'
# Use the Puma web server [https://github.com/puma/puma]
gem 'puma', '>= 5.0'
# Build JSON APIs with ease [https://github.com/rails/jbuilder]
# gem 'jbuilder'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '>= 4.0.1'

# Use Kredis to get higher-level data types in Redis [https://github.com/rails/kredis]
# gem 'kredis'

# Use Active Model has_secure_password
# [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
# gem 'bcrypt', '~> 3.1.7'

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: %i[windows jruby]

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', require: false

# Use Active Storage variants
# [https://guides.rubyonrails.org
# /active_storage_overview.html#transforming-images]
# gem 'image_processing', '~> 1.2'

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS),
# making cross-origin Ajax possible
# gem 'rack-cors'

group :development, :test do
  gem 'byebug', platform: :mri
  # Static analysis for security vulnerabilities [https://brakemanscanner.org/]
  gem 'brakeman', require: false
  gem 'factory_bot_rails', '~> 6.5'
  gem 'faker', '~> 3.5'
  gem 'letter_opener_web'

  gem 'rspec-rails', '~> 8.0'
  gem 'simplecov', '~> 0.22.0'
  # Omakase Ruby styling [https://github.com/rails/rubocop-rails-omakase/]
  gem 'rubocop-rails-omakase', require: false
end

group :development do
  gem 'annotaterb'
  gem 'dotenv-rails', '~> 3.1'
  gem 'rubocop', '~> 1.79', require: false # false para evitar
  # se cargue en entornos de produccion
  gem 'rubocop-performance', '~> 1.25', require: false # Para cops de rendimient
  gem 'rubocop-rails', '~> 2.32', require: false # Para reglas de Rails
  gem 'rubocop-rspec', '~> 3.6', require: false # Si usas RSpec para tus pruebas
end

group :test do
  gem 'database_cleaner-active_record', '~> 2.2'
  gem 'shoulda-matchers', '~> 6.5'
end

gem 'rack-cors'

gem 'devise'
gem 'devise_token_auth'

gem 'google-id-token'
